dist: xenial
services:
  - postgresql
sudo: required
branches:
  only:
  - master
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - python manage.py test --keepdb 
deploy:
  provider: heroku
  app: examen1819-830-juaferfer11 
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: master
